const data = {
    entries: [
        {
            _id: '156531',
            user_id: 'user 0',
            mood: 'Regular',
            diary: 'Specifies text alignment. On Android, the value "justify" is only supported on Oreo (8.0) or above (API level >= 26). The value will fallback to left on lower Android versions.',
            emotions: ['anxious', 'depressed', 'tired'],
            date: '10-15-21',
            time: '11:26 PM',
            address: 'Rua Doutor Celestino, 42 - Centro',
        },
        {
            _id: '156531',
            user_id: 'user 0',
            mood: 'Regular',
            diary: 'Specifies text alignment. On Android, the value justify is only supported on Oreo (8.0) or above API level >= 26). The value will fallback to left on lower Android versions.',
            emotions: ['anxious', 'depressed', 'tired'],
            date: '10-15-21',
            time: '11:26 PM',
            address: 'Rua Doutor Celestino, 42 - Centro',
        },
        {
            _id: '156531',
            user_id: 'user 0',
            mood: 'Regular',
            diary: 'Specifies text alignment. On Android, the value "justify" is only supported on Oreo (8.0) or above (API level >= 26). The value will fallback to left on lower Android versions.',
            emotions: ['anxious', 'depressed', 'tired'],
            date: '10-15-21',
            time: '12:26 AM',
            address: 'Rua Doutor Celestino, 42 - Centro',
        },
        {
            _id: '156531',
            user_id: 'user 0',
            mood: 'Regular',
            diary: 'Specifies text alignment. On Android, the value "justify" is only supported on Oreo (8.0) or above (API level >= 26). The value will fallback to left on lower Android versions.',
            emotions: ['anxious', 'depressed', 'tired'],
            date: '10-15-21',
            time: '12:26 AM',
            address: 'Rua Doutor Celestino, 42 - Centro',
        },
        {
            _id: '156531',
            user_id: 'user 0',
            mood: 'Regular',
            diary: 'Specifies text alignment. On Android, the value "justify" is only supported on Oreo (8.0) or above (API level >= 26). The value will fallback to left on lower Android versions.',
            emotions: ['anxious', 'depressed', 'tired'],
            date: '10-15-21',
            time: '12:26',
            address: 'Rua Doutor Celestino, 42 - Centro',
        },
        {
            _id: '156531',
            user_id: 'user 0',
            mood: 'Regular',
            diary: 'Specifies text alignment. On Android, the value "justify" is only supported on Oreo (8.0) or above (API level >= 26). The value will fallback to left on lower Android versions.',
            emotions: ['anxious', 'depressed', 'tired'],
            date: '10-15-21',
            time: '12:26',
            address: 'Rua Doutor Celestino, 42 - Centro',
        },
    ]
}
export default data;